amcl:
  ros__parameters:
    use_sim_time: true   # not used, safe to keep

# -------------------------
# BT Navigator
# -------------------------
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: odom          # NO MAP → use odom
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    # default_nav_to_pose_bt_xml: /home/alberthtran/ros2_project/src/nav2_simple_navigation/behavior_tree/drive_in_circle.xml

# -------------------------
# Planner Server
# -------------------------
planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 10.0

    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false

# -------------------------
# Controller Server (MPPI)
# -------------------------
controller_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: true
    controller_frequency: 20.0
    odom_topic: /odometry/filtered

    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_velocity: 0.5
      lookahead_dist: 0.6       # Crucial: smaller = tighter turns, larger = smoother
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.0
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: false # Set to false since you're in an empty space
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.1

# -------------------------
# Global Costmap (no map)
# -------------------------
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true

      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true  # Essential for empty space/no-map
      width: 10
      height: 10
      resolution: 0.05

      plugins: ["inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

# -------------------------
# Local Costmap
# -------------------------
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true

      global_frame: odom
      robot_base_frame: base_link

      resolution: 0.05

      # IMPORTANT for local behavior
      rolling_window: true
      width: 3
      height: 3

      plugins: ["inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

# -------------------------
# Recovery Server
# -------------------------

recoveries_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_realtime_priority: false

# -------------------------
# Lifecycle Manager
# -------------------------
lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true

    node_names: [
      'global_costmap/global_costmap',
      'local_costmap/local_costmap',
      "planner_server",
      "controller_server",
      "bt_navigator"
    ]

    bond_timeout: 10.0
    attempt_respawn_reconnection: true
    bond_respawn_max_duration: 10.0